service: aws-python-flask-api
frameworkVersion: '3'
custom:
  wsgi:
    app: app.app
    packRequirements: false
provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  api:
    handler: wsgi.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
