name:  Dev API Build
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        node-version: [16.x]
    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "The workflow is now ready to test your code on the runner."
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set node packagerOptions
      run: export NODE_OPTIONS=--max_old_space_size=8192
    - name: Install npm dependencies
      run: npm install
    - run: echo "npm dependencies install success"
    - name: Install npm global tool
      run: npm install -g node-prune modclean
    - name: Remove npm unnecessary files
      run: node-prune
    - name: Cleanup node_modules
      run: modclean -n default:safe,default:caution -
    - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt       
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
