name:  Dev API Build
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [16.x]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "The workflow is now ready to test your code on the runner."
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Serverless Framework
      run: npm install -g serverless@2
    - name: Install npm dependencies
      run: npm install
   
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: ${{matrix.python-version}}
    # - name: Install Python dependencies
    #   run: |
    #     python -m pip install
    #     pip install -r requirements.txt      


    # - name: Initialize Python 3.9
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.9'
    #     cache: 'pip' 
    # - run: pip install -r requirements.txt
    # - run: echo "python --version"
    # - name: serverless deploy
    #   uses: serverless/github-action@v3.1
    #   with:
    #     args: deploy
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        run: echo "python --version"
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

